# Generated by Django 2.1.2 on 2020-03-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MakanakModels', '0002_auto_20200302_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='postalcode',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='postalcode'),
        ),
    ]
